### ISSUE TITLE
Add ability to send error codes explicitly through libpay

### ISSUE THREAD

**Issue by ymakhno** [wix/libpay#6]
Currently error code which libpay receives from provider is usually part of message inside `PaymentRejectedException` and `PaymentErrorException`. Such implementation doesn't allow us to build any specific logic around error codes in services which are using libpay as a library. 

Our request is to add optional parameter to `PaymentRejectedException` and `PaymentErrorException` and allow to specify error codes there explicitly not inside message. 

Example: 
`case class PaymentRejectedException(message: String, cause: Throwable, errorCode: Option[String] = None)`

**Comment by dleshem** [comment]
libpay main purpose is to abstract payment gateways, i.e. make the user as oblivious as possible to which actual payment gateway is used. Exposing internal error codes would be a leaky abstraction.

From our chat earlier, I understand that you're looking for more fine-grained error messages. For example, you mentioned that Stripe requires payment amounts to be above some minimum, and you want to let the buyer know that's why their payment failed.

A non leaky abstraction would be to add, say, ```AmountBelowMinimumException extends PaymentRejectedException```. Perhaps we should add a bunch of these common exceptions.

Would this work for you?

**Comment by ymakhno** [comment]
@dleshem we want to know why transaction is failed on provider side, to be able to save provider error codes on BI and do some research based on it plus provider error on our side explicitly to have ability to communicate with provider support.

>Exposing internal error codes would be a leaky abstraction.

I can't agree with you on that. Libpay returns `transactionId` which is fully provider specific on each successful `sale` or `authorize` and this information answers question **how** transaction was approved by provider (in successful case). And errorCode answers question **how** transaction was declined by provider (in failure case), and we currently can't receive this information through libpay. 

I think it's good to compare libpay for example with JDBC - which is also library that abstracts DB operations for all relational databases in Java. JDBC allows you to get vendor specific error code in case of failures: https://docs.oracle.com/javase/7/docs/api/java/sql/SQLException.html

>Perhaps we should add a bunch of these common exceptions. Would this work for you?

No, we are really interested to know provider specific code, because libpay is a library which we use to _communicate_ with provider, but we are _doing_ payments through provider and not through libpay.

**Comment by dleshem** [comment]
Good point regarding JDBC's ```vendorCode```.

I agree that it makes sense to expose a ```gatewayCode``` for BI / reporting / debugging purposes.

However, having to write *logic* based on that internal code would be a signal that libpay is incomplete. I assume the logic you want to implement would be shared for several different vendor-specific codes, for example you'll show an "amount below minimum" error message for Stripe internal code 17, and for MercadoPago internal code 55. If that's the case, I really think this should be abstracted by new exception types in libpay.

WDYT?

@ohadraz, I'd love to get your feedback here.

**Comment by ohadraz** [comment]
I think that, indeed, JDBC's `vendorCode` is a good reference for this discussion.
The idea is to let the DB vendor add its own error codes to the (too) general SQL exception. It is up to the vendor to do that, and in any case, it is optional (defaults to 0).

Now let's check what's up that:
_Oracle_ provide vendor codes,
_MySql_ provide vendor codes. 
_MS SQL Server_, if I can recall (and it was around a decade ago),  **does not** provide vendor codes.
_Postgres_ **does not** provide vendor codes as well (maybe because Postgres' error codes are alphanumeric, while `vendorCode` is an `int`, I don't know).

That is to say, that being _optional_, many (at least, some) vendors do not populate the `vendorCode` property. 
Among those that "abuse" the field being optional, are not just small vendors, but also big,  mainstream, leading players.
And this whole thing happens in the super bureaucratic, serious and heavy industry of relational DB.

Now, back to the our world. 
I guess we all have implemented one or two gateways, and so it is fair to say that we all know that documentation and standards are sub-optimal... 
I am willing to put a 100$ bet with each of you, @dleshem and @ymakhno, that the vast majority of gateways will simply not populate this property.
And so, _practically_ - I think introducing such a property will prove be useless in many, many cases.

On the other hand, a more concrete exception, in this case, would be preferable. I believe that most chances are that gateways will raise the concrete exception, if available, once encountering a specific error on their end.
And so, _practically_ - I think concrete exceptions are the right path to go.

_Philosophically_, when I refer to what @ymakhno says, regarding the `transactionId` exposing **how** transaction was approved - I do not see it this way. The transaction ID does not expose the "how"; it is merely a "foreign key" to whatever process or data the provider holds.

And finally - scope and responsibility. It is not the scope nor responsibility of libpay to be aware of any BI/reporting tools or mechanism. It is the **caller**'s responsibility - in our case, the _pay-direct_. 
None, not libpay nor pay-direct, is aware or holds responsibility for the communication with the provider support upon hitting a failure. This communication thingy is an offline, non automated, **human** interface.
And so, _philosophically_ - I do not think the concerns raised by @ymakhno are relevant to libpay.

And yet - BI, reporting and debugging are super important, and I fully understand the need.
So what do I think, bottom line?

- Identify the common errors, and introduce an exception to each in libpay
- Use the exceptions thrown by libpay to report our BI/Anodot/Relic/Grafana/whatever from _pay-direct_ (include the exception and the gateway ID)
- Have a KB/GitHub/Whatever that maps exception -> gateway ID pair to the gateways internal error code, for communication purposes (of course, if you have spare time on your hands you can write a tool that reads BI reports, and "translate" it to provider specific error codes).

**Comment by ymakhno** [comment]
@ohadraz @dleshem 
Again, what we are really interested in is to see provider error code, we are not interested in common errors provided by libpay. Libpay is not payment processor, it's just a library which should allow you to understand what happened on provider side.

Also I don't think exception per error would be usable from developers prospective... Just imagine this catch block with 20-60 different exception. So IMO this decision won't solve our problem and will be unusable for other developers as well.

**Comment by ymakhno** [comment]
@ohadraz regarding JDBC, I don't think that something is wrong if some gateway doesn't populate the property, it's **possibility** and not **rule**, library is to provide possibilities 🙂

**Comment by artempWix** [comment]
@dleshem so is it possible to add an optional parameter to these exceptions?

**Comment by dleshem** [comment]
Fixed in https://github.com/wix/libpay/commit/23899a9f3aaf1201c8712a220e504aa014eb6e6d.

> `gatewayInternalCode` is an optional, opaque, gateway-specific error code for debugging, logging, and analytics. Do not rely on this for business logic: values and format are treated as implementation detail and may change without notice.
